export default {
  thumbMask: require('./thumb-mask.png'),
  colorPicker: require('./color-picker.png'),
  colorBg: require('./color-bg.png'),
  light: require('./light.png'),
  lamp: require('./lamp.png'),
  startIcon: require('./startIcon.png'),
  stopIcon: require('./stopIcon.png'),
  musicMask: require('./musicMask.png'),
  app_music_music: require('./app_music_music.png'),
  app_music_ball: require('./app_music_ball.png'),
  app_music_game: require('./app_music_game.png'),
  app_music_romantic: require('./app_music_romantic.png'),
  mode1: require('./mode1.png'),
  mode2: require('./mode2.png'),
  stopIconLight: require('./stopIcon_light.png'),
  startIconLight: require('./startIcon_light.png'),
  timeBg: require('./timeBg.png'),
  disturbBg: require('./disturbBg.png'),
  colorCard_colour: require('./colorCard_colour.png'),
};
