const defaultData = {
  version: 0,
  power: false,
  mode: 0,
  weeks: [1, 1, 1, 1, 1, 1, 1, 0],
  number: 6,
  rhythms: [
    {
      power: true,
      hour: 6,
      minute: 0,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 0,
      temperature: 100,
    },
    {
      power: true,
      hour: 6,
      minute: 30,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 100,
      temperature: 50,
    },
    {
      power: true,
      hour: 11,
      minute: 30,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 100,
      temperature: 100,
    },
    {
      power: true,
      hour: 17,
      minute: 0,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 70,
      temperature: 50,
    },
    {
      power: true,
      hour: 20,
      minute: 30,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 70,
      temperature: 50,
    },
    {
      power: true,
      hour: 21,
      minute: 0,
      hue: 0,
      saturation: 0,
      value: 0,
      brightness: 0,
      temperature: 0,
    },
  ],
};
export default defaultData;
