export default {
  sleepCode: 'sleep_mode',
  wakeUpCode: 'wakeup_mode',
  powerCode: 'switch_led',
  colourCode: 'colour_data',
  workModeCode: 'work_mode',
  temperatureCode: 'temp_value',
  brightCode: 'bright_value',
  sceneCode: 'scene_data',
  musicCode: 'music_data',
  countdownCode: 'countdown',
  controlCode: 'control_data',
  rhythmCode: 'rhythm_mode',
  cycleTimingCode: 'cycle_timing',
  randomTimingCode: 'random_timing',
  powerMemoryCode: 'power_memory',
  doNotDisturbCode: 'do_not_disturb',
} as DpCodes;
