name: Upload lamp coverage to Codecov
on: push
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: build
        run: yarn run build
      - name: Run Test
        run: npx lerna run test:lamp -- --silent --forceExit --passWithNoTests
      - name: Upload lamp coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: lamp
          directory: ./packages/tuya-panel-lamp-sdk/coverage/
