name: jest
on:
  push:
    branches:
      - main # Change this to your default branch
  pull_request:
    branches:
      - main # Change this to your default branch
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install modules
        run: yarn --frozen-lockfile --ignore-engines --ignore-optional --no-bin-links --non-interactive --silent --ignore-scripts --production=false
      - name: build
        run: yarn run build
      - name: Run Test
        run: yarn test --silent --forceExit --passWithNoTests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
