name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: Run Test
        run: yarn test --silent --forceExit --passWithNoTests
      - name: Upload animation coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: animation
          directory: ./tuya-panel-animation-sdk/coverage/
