name: Upload robot coverage to Codecov
on: push
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: build
        run: yarn run build
      - name: Run Test
        run: cd packages/tuya-panel-robot-sdk && yarn test --silent --forceExit
      - name: Upload robot coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: robot
          directory: ./packages/tuya-panel-robot-sdk/coverage/
