name: Upload coverage to Codecov
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: Run Test
        run: npx lerna run test -- --silent --forceExit --passWithNoTests
      - name: Upload animation coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: animation
          directory: ./packages/tuya-panel-animation-sdk/coverage/
      - name: Upload ipc coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: ipc
          directory: ./packages/tuya-panel-ipc-sdk/coverage/
      - name: Upload robot coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: robot
          directory: ./packages/tuya-panel-robot-sdk/coverage/
      - name: Upload api coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: electrician
          directory: ./packages/tuya-panel-electrician-sdk/coverage/
