name: Upload ipc coverage to Codecov
on: push
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: build
        run: yarn run build
      - name: Run Test
        run: cd packages/tuya-panel-ipc-sdk && yarn test --silent --forceExit --passWithNoTests
      - name: Upload ipc coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          override_branch: ipc
          directory: ./packages/tuya-panel-ipc-sdk/coverage/
