name: Upload coverage to Codecov
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: Run Test
        run: npx lerna run test -- --silent --forceExit --passWithNoTests
      - name: ls
        run: cd ./packages/tuya-panel-animation-sdk/coverage/ && ls
      - name: Upload animation coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: animation
          directory: ./packages/tuya-panel-animation-sdk/coverage/
