name: jest
on: push
jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: build
        run: yarn run build
      - name: Run Test
        run: yarn test --silent --forceExit --passWithNoTests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
