name: Send notification on pull_request
on: pull_request

jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
      - name: WeChat Work notification by markdown
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "${{github.event.sender.login}} ${{github.event.action}} [tuya/tuya-panel-sdk/pull/${{github.event.number}}](https://github.com/tuya/tuya-panel-sdk/pull/${{github.event.number}}) \n
          > wants to merge ${{github.event.pull_request.commits}} commits from ${{github.head_ref}} into ${{github.base_ref}} \n
          > commits: <font color=\"comment\">${{github.event.pull_request.commits}}</font> \n
          > changed_files: <font color=\"comment\">${{github.event.pull_request.changed_files}}</font>"
          mentioned_list: '["@all"]'
